In [258]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load dataset

In [259]:
test_df = pd.read_csv("./test.csv")
train_df = pd.read_csv("./train.csv")

In [260]:
train_df.head(1)

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male 22.00      1   

   Parch     Ticket  Fare Cabin Embarked  
0      0  A/5 21171  7.25   NaN        S

In [261]:
test_df.head(1)

PassengerId  Pclass              Name   Sex   Age  SibSp  Parch  Ticket  \
0          892       3  Kelly, Mr. James  male 34.50      0      0  330911   

   Fare Cabin Embarked  
0  7.83   NaN        Q

In [262]:
train_df.set_index('PassengerId', inplace=True)
test_df.set_index('PassengerId', inplace=True)

In [263]:
train_df.head(1)

Survived  Pclass                     Name   Sex   Age  SibSp  \
PassengerId                                                                 
1                   0       3  Braund, Mr. Owen Harris  male 22.00      1   

             Parch     Ticket  Fare Cabin Embarked  
PassengerId                                         
1                0  A/5 21171  7.25   NaN        S

In [264]:
test_df.head(1)

Pclass              Name   Sex   Age  SibSp  Parch  Ticket  Fare  \
PassengerId                                                                     
892               3  Kelly, Mr. James  male 34.50      0      0  330911  7.83   

            Cabin Embarked  
PassengerId                 
892           NaN        Q

In [265]:
train_index = train_df.index
test_index = test_df.index

In [266]:
y_train_df = train_df.pop("Survived")

In [267]:
y_train_df.head(3)

PassengerId
1    0
2    1
3    1
Name: Survived, dtype: int64

In [268]:
train_df.head(3)

Pclass                                               Name  \
PassengerId                                                              
1                 3                            Braund, Mr. Owen Harris   
2                 1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
3                 3                             Heikkinen, Miss. Laina   

                Sex   Age  SibSp  Parch            Ticket  Fare Cabin Embarked  
PassengerId                                                                     
1              male 22.00      1      0         A/5 21171  7.25   NaN        S  
2            female 38.00      1      0          PC 17599 71.28   C85        C  
3            female 26.00      0      0  STON/O2. 3101282  7.92   NaN        S

# Data preprocessing

In [269]:
pd.set_option('display.float_format', lambda x: '%.2f' % x) #float format 소수점 둘째자리까지로 바꾸기

In [270]:
test_df.isnull()

Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  \
PassengerId                                                                    
892           False  False  False  False  False  False   False  False   True   
893           False  False  False  False  False  False   False  False   True   
894           False  False  False  False  False  False   False  False   True   
895           False  False  False  False  False  False   False  False   True   
896           False  False  False  False  False  False   False  False   True   
...             ...    ...    ...    ...    ...    ...     ...    ...    ...   
1305          False  False  False   True  False  False   False  False   True   
1306          False  False  False  False  False  False   False  False  False   
1307          False  False  False  False  False  False   False  False   True   
1308          False  False  False   True  False  False   False  False   True   
1309          False  False  False   True  False  False   False  False   True   

             Embarked  
PassengerId            
892             False  
893             False  
894             False  
895             False  
896             False  
...               ...  
1305            False  
1306            False  
1307            False  
1308            False  
1309            False  

[418 rows x 10 columns]

In [271]:
test_df.isnull().sum() / len(test_df) *100

Pclass      0.00
Name        0.00
Sex         0.00
Age        20.57
SibSp       0.00
Parch       0.00
Ticket      0.00
Fare        0.24
Cabin      78.23
Embarked    0.00
dtype: float64

In [272]:
train_df.isnull().sum() / len(train_df) * 100

Pclass      0.00
Name        0.00
Sex         0.00
Age        19.87
SibSp       0.00
Parch       0.00
Ticket      0.00
Fare        0.00
Cabin      77.10
Embarked    0.22
dtype: float64

### Decision 1 - Drop cabin

In [273]:
del test_df["Cabin"]
del train_df["Cabin"]

In [274]:
all_df = train_df.append(test_df)
all_df

Pclass                                               Name  \
PassengerId                                                              
1                 3                            Braund, Mr. Owen Harris   
2                 1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
3                 3                             Heikkinen, Miss. Laina   
4                 1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
5                 3                           Allen, Mr. William Henry   
...             ...                                                ...   
1305              3                                 Spector, Mr. Woolf   
1306              1                       Oliva y Ocana, Dona. Fermina   
1307              3                       Saether, Mr. Simon Sivertsen   
1308              3                                Ware, Mr. Frederick   
1309              3                           Peter, Master. Michael J   

                Sex   Age  SibSp  Parch              Ticket   Fare Embarked  
PassengerId                                                                  
1              male 22.00      1      0           A/5 21171   7.25        S  
2            female 38.00      1      0            PC 17599  71.28        C  
3            female 26.00      0      0    STON/O2. 3101282   7.92        S  
4            female 35.00      1      0              113803  53.10        S  
5              male 35.00      0      0              373450   8.05        S  
...             ...   ...    ...    ...                 ...    ...      ...  
1305           male   nan      0      0           A.5. 3236   8.05        S  
1306         female 39.00      0      0            PC 17758 108.90        C  
1307           male 38.50      0      0  SOTON/O.Q. 3101262   7.25        S  
1308           male   nan      0      0              359309   8.05        S  
1309           male   nan      1      1                2668  22.36        C  

[1309 rows x 9 columns]

In [275]:
del all_df["Name"]

In [276]:
del all_df["Ticket"]

In [277]:
all_df.head()

Pclass     Sex   Age  SibSp  Parch  Fare Embarked
PassengerId                                                   
1                 3    male 22.00      1      0  7.25        S
2                 1  female 38.00      1      0 71.28        C
3                 3  female 26.00      0      0  7.92        S
4                 1  female 35.00      1      0 53.10        S
5                 3    male 35.00      0      0  8.05        S

In [278]:
all_df["Sex"] = all_df["Sex"].replace({"male":0,"female":1})

In [279]:
all_df.head()

Pclass  Sex   Age  SibSp  Parch  Fare Embarked
PassengerId                                                
1                 3    0 22.00      1      0  7.25        S
2                 1    1 38.00      1      0 71.28        C
3                 3    1 26.00      0      0  7.92        S
4                 1    1 35.00      1      0 53.10        S
5                 3    0 35.00      0      0  8.05        S

In [280]:
all_df["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [281]:
all_df["Embarked"] = all_df["Embarked"].replace({"S":0,"C":1,"Q":2, np.nan:99})

In [282]:
all_df["Embarked"].unique()

array([ 0,  1,  2, 99], dtype=int64)

In [283]:
all_df.head()

Pclass  Sex   Age  SibSp  Parch  Fare  Embarked
PassengerId                                                 
1                 3    0 22.00      1      0  7.25         0
2                 1    1 38.00      1      0 71.28         1
3                 3    1 26.00      0      0  7.92         0
4                 1    1 35.00      1      0 53.10         0
5                 3    0 35.00      0      0  8.05         0

In [284]:
pd.get_dummies(all_df["Embarked"], prefix="embarked")

embarked_0  embarked_1  embarked_2  embarked_99
PassengerId                                                 
1                     1           0           0            0
2                     0           1           0            0
3                     1           0           0            0
4                     1           0           0            0
5                     1           0           0            0
...                 ...         ...         ...          ...
1305                  1           0           0            0
1306                  0           1           0            0
1307                  1           0           0            0
1308                  1           0           0            0
1309                  0           1           0            0

[1309 rows x 4 columns]

In [285]:
matrix_df = pd.merge(
    all_df, pd.get_dummies(all_df["Embarked"], prefix="embarked"), 
    left_index=True, right_index=True)
matrix_df.head()

Pclass  Sex   Age  SibSp  Parch  Fare  Embarked  embarked_0  \
PassengerId                                                                
1                 3    0 22.00      1      0  7.25         0           1   
2                 1    1 38.00      1      0 71.28         1           0   
3                 3    1 26.00      0      0  7.92         0           1   
4                 1    1 35.00      1      0 53.10         0           1   
5                 3    0 35.00      0      0  8.05         0           1   

             embarked_1  embarked_2  embarked_99  
PassengerId                                       
1                     0           0            0  
2                     1           0            0  
3                     0           0            0  
4                     0           0            0  
5                     0           0            0

In [286]:
all_df.groupby("Pclass")["Age"].mean()

Pclass
1   39.16
2   29.51
3   24.82
Name: Age, dtype: float64

In [287]:
all_df.groupby("Sex")["Age"].mean()

Sex
0   30.59
1   28.69
Name: Age, dtype: float64

In [288]:
all_df.loc[(all_df["Pclass"] == 1) & (all_df["Age"].isnull()) , "Age"]
#Pclass가 1이고 Age가 Nan인 사람의 Age

PassengerId
32     nan
56     nan
65     nan
167    nan
169    nan
186    nan
257    nan
271    nan
285    nan
296    nan
299    nan
307    nan
335    nan
352    nan
376    nan
458    nan
476    nan
508    nan
528    nan
558    nan
603    nan
634    nan
670    nan
712    nan
741    nan
767    nan
794    nan
816    nan
840    nan
850    nan
914    nan
933    nan
1038   nan
1040   nan
1060   nan
1083   nan
1097   nan
1158   nan
1182   nan
Name: Age, dtype: float64

In [289]:
all_df.loc[(all_df["Pclass"] == 1) & (all_df["Age"].isnull()), "Age"] = 39.16
all_df.loc[(all_df["Pclass"] == 2) & all_df["Age"].isnull() , "Age"] = 29.51
all_df.loc[( all_df["Pclass"] == 3) & all_df["Age"].isnull(), "Age"] = 24.82

In [290]:
all_df.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        1
Embarked    0
dtype: int64

In [291]:
all_df.groupby("Pclass")["Fare"].mean()

Pclass
1   87.51
2   21.18
3   13.30
Name: Fare, dtype: float64

In [292]:
all_df[all_df["Fare"].isnull()]

Pclass  Sex   Age  SibSp  Parch  Fare  Embarked
PassengerId                                                 
1044              3    0 60.50      0      0   nan         0

In [293]:
all_df.loc[all_df["Fare"].isnull(), "Fare"] = 13.30

In [294]:
del all_df["Embarked"]

In [295]:
all_df["Pclass"] = all_df["Pclass"].replace({1:"A",2:"B",3:"C"})

In [296]:
all_df = pd.get_dummies(all_df)
all_df.head()

Sex   Age  SibSp  Parch  Fare  Pclass_A  Pclass_B  Pclass_C
PassengerId                                                             
1              0 22.00      1      0  7.25         0         0         1
2              1 38.00      1      0 71.28         1         0         0
3              1 26.00      0      0  7.92         0         0         1
4              1 35.00      1      0 53.10         1         0         0
5              0 35.00      0      0  8.05         0         0         1

In [297]:
all_df = pd.merge(
    all_df, matrix_df[["embarked_0", "embarked_1", "embarked_2", "embarked_99"]], 
    left_index=True, right_index=True)

In [298]:
train_df = all_df[all_df.index.isin(train_index)]
test_df = all_df[all_df.index.isin(test_index)]

In [302]:
train_df.head(3)

Sex   Age  SibSp  Parch  Fare  Pclass_A  Pclass_B  Pclass_C  \
PassengerId                                                                
1              0 22.00      1      0  7.25         0         0         1   
2              1 38.00      1      0 71.28         1         0         0   
3              1 26.00      0      0  7.92         0         0         1   

             embarked_0  embarked_1  embarked_2  embarked_99  
PassengerId                                                   
1                     1           0           0            0  
2                     0           1           0            0  
3                     1           0           0            0

In [303]:
test_df.head(3)

Sex   Age  SibSp  Parch  Fare  Pclass_A  Pclass_B  Pclass_C  \
PassengerId                                                                
892            0 34.50      0      0  7.83         0         0         1   
893            1 47.00      1      0  7.00         0         0         1   
894            0 62.00      0      0  9.69         0         1         0   

             embarked_0  embarked_1  embarked_2  embarked_99  
PassengerId                                                   
892                   0           0           1            0  
893                   1           0           0            0  
894                   0           0           1            0

## Build Model

In [304]:
x_data = train_df.values
y_data = y_train_df.values

In [305]:
x_data.shape, y_data.shape

((891, 12), (891,))

In [306]:
y_data

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [307]:
from sklearn.linear_model import LogisticRegression
cls = LogisticRegression()
cls.fit(x_data,y_data)

C:\Users\public\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [308]:
cls.intercept_

array([0.18829674])

In [309]:
cls.coef_

array([[ 2.60750665e+00, -4.07586678e-02, -3.25647165e-01,
        -8.49180077e-02,  2.48637600e-03,  1.11465026e+00,
         1.52999437e-01, -1.07935295e+00, -2.45258166e-01,
         1.66095755e-01,  6.65916090e-02,  2.00867547e-01]])

In [310]:
cls.predict(test_df.values)

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [315]:
x_test = test_df.values
y_test =cls.predict(x_test)
y_test

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [312]:
result = np.concatenate( (test_index.values.reshape(-1,1),
                 cls.predict(x_test).reshape(-1,1)  ) , axis=1)
result[:5]

array([[892,   0],
       [893,   0],
       [894,   0],
       [895,   0],
       [896,   1]], dtype=int64)

In [313]:
df_submssion =pd.DataFrame(result, columns=["PassengerId","Survived"])
df_submssion

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [314]:
df_submssion.to_csv("submission_result.csv",index=False)